import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} mx-24 h-full`}>
        <div className="min-h-screen bg-[url('/assets/bg.png')] bg-cover bg-center">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
